site_name: ClusterSecret
theme:
  name: material
  logo: assets/csninjasmall.png
  favicon: assets/csninjaicon.png
repo_url: https://github.com/zakkg3/ClusterSecret
site_url: https://clustersecret.io
edit_uri: https://github.com/zakkg3/ClusterSecretDocs/edit/main/docs/
nav:
    - ClusterSecret: 'index.md'
    - 'Install': 'install.md'
    - 'Quick Start': 'quickstart.md'
    - 'Configuration': 'config.md'
    - 'Value from Secret': 'valuefromsecret.md'
    - 'Develop & Debug': 'dev.md'
    - 'Join on slack': 'joincommunity.md'
    - 'Roadmap': 'roadmap.md'
    - 'Help & Support': 'support.md'
markdown_extensions:
  - attr_list
  - md_in_html
extra:
  analytics:
    provider: google
    property: G-5XW45WBMDL
  
