site_name: ClusterSecret
theme:
  name: material
repo_url: https://github.com/zakkg3/ClusterSecret
site_url: https://cs.flag5.com
markdown_extensions:
  - attr_list
  - md_in_html
extra:
  analytics:
    provider: google
    property: G-ZYNQ87PV7E
